[package]
name = "cymbal"
version = "0.1.0"
authors = ["Matt Hooper <matthewjhooper94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
num-traits = "0.2.11"
num-bigint = "0.2.6"